name: Check Documentation links 

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Install lychee
        run: cargo install lychee
      
      - name: Check links
        run: lychee --verbose --root-dir 'website/docs/**/*.md'